export interface Song {
  id: string;
  title: string;
  artist: string;
  category: string;
  featured: boolean;
  hotComment?: string;
}

// 以后只需在这里增删歌曲或修改 featured；id 一旦投入使用请保持不变，以保留累计点歌数。
export const SONGS: Song[] = [
  { id: 'qing-tian', title: '晴天', artist: '周杰伦', category: '华语流行', featured: true, hotComment: '故事的小黄花，从出生那年就飘着' },
  { id: 'qing-hua-ci', title: '青花瓷', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '天青色等烟雨，而我在等你' },
  { id: 'deng-ni-xia-ke', title: '等你下课', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '复读时我要好好学习，考上和你一样的大学' },
  { id: 'hong-chen-ke-zhan', title: '红尘客栈', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '红尘客栈风似刀，骤雨落宿命敲' },
  { id: 'gao-bai-qi-qiu', title: '告白气球', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '少年的脸红胜过一切情话' },
  { id: 'yi-lu-xiang-bei', title: '一路向北', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '拓海跑赢了所有人，但还是输给了那辆奔驰' },
  { id: 'hua-hai', title: '花海', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '听说，花海的前奏和晴天一样好听' },
  { id: 'pu-gong-ying-de-yue-ding', title: '蒲公英的约定', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '而我已经分不清，你是友情，还是错过的爱情' },
  { id: 'ming-ming-jiu', title: '明明就', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '她明明就只是看了你一眼，你却在心里演了无数场电影' },
  { id: 'feng', title: '枫', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '天冷的季节听这首歌，会有不一样的感觉。' },
  { id: 'bu-neng-shuo-de-mi-mi', title: '不能说的秘密', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '最美的不是下雨天🌧️，而是与你躲过雨的屋檐' },
  { id: 'ge-qian', title: '搁浅', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '后半段升调很好听是真的，但唱不上去也是真的！' },
  { id: 'lan-ting-xu', title: '兰亭序', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '喜欢王羲之的兰亭集序，也喜欢杰伦的兰亭序' },
  { id: 'shou-xie-de-cong-qian', title: '手写的从前', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '青春属于表白，阳光属于窗台，而我想我属于一个拥有你的未来' },
  { id: 'ban-dao-tie-he', title: '半岛铁盒', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '小姐请问一下，有没有卖半岛铁盒？' },
  { id: 'wo-luo-lei-qing-xu-ling-sui', title: '我落泪情绪零碎', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '七里香的姐妹曲' },
  { id: 'na-tian-xia-yu-le', title: '那天下雨了', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '从晴天的遗憾，到那天下雨了的和解' },
  { id: 'jian-dan-ai', title: '简单爱', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '我想带你回我的外婆家，一起看着日落，一直到我们都睡着' },
  { id: 'yuan-you-hui', title: '园游会', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '有钱的时候跑到塞纳河畔喝咖啡，没钱的时候就只能去园游会捞鱼了' },
  { id: 'xia-tian-de-feng', title: '夏天的风', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '杰伦15岁时做出来的曲子，《夏天》给了李玖哲，《夏天的风》给了温岚' },
  { id: 'zui-chang-de-dian-ying', title: '最长的电影', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '那年学校晚会在台上这首歌，看到喜欢的女孩和男朋友在角落kiss，边唱边落泪，观众都以为我唱得太投入了' },
  { id: 'long-juan-feng', title: '龙卷风', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '龙卷风刮了二十多年了，依然没停' },
  { id: 'yan-hua-yi-leng', title: '烟花易冷', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '雨纷纷，旧故里草木深，我听闻你始终一个人' },
  { id: 'tui-hou', title: '退后', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '喜欢周杰伦26年了，从少女到妇女，算算也有大半辈子了' },
  { id: 'dao-dai', title: '倒带', artist: '周杰伦', category: '华语流行', featured: false, hotComment: 'Jolin不仅是公主，更是女王' },
  { id: 'an-jing', title: '安静', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '老师：安静！我：哟不错哦，挺有品味的' },
  { id: 'cai-hong', title: '彩虹', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '这是我和妻子在一起时合唱的第一首歌' },
  { id: 'na-li-dou-shi-ni', title: '哪里都是你', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '在有眼泪的雨里，哪里都是你' },
  { id: 'gui-ji', title: '轨迹', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '头低低先生和微微笑小姐' },
  { id: 'shuo-hao-de-xing-fu-ne', title: '说好的幸福呢', artist: '周杰伦', category: '华语流行', featured: false, hotComment: '20160204：初中时，家里，学校广播，大街小巷，都是这首歌！' },
  { id: 'jiang-nan', title: '江南', artist: '林俊杰', category: '华语流行', featured: false, hotComment: '一把木吉他，也能把江南的风雨唱得很美。' },
  { id: 'xin-qiang', title: '心墙', artist: '林俊杰', category: '华语流行', featured: false, hotComment: '有些心墙不是为了拒绝，而是在等一个温柔的敲门声。' },
  { id: 'dang-ni', title: '当你', artist: '林俊杰', category: '华语流行', featured: false, hotComment: '喜欢一个人时，连想象都带着甜味。' },
  { id: 'xiu-lian-ai-qing', title: '修炼爱情', artist: '林俊杰', category: '华语流行', featured: false, hotComment: '爱情最难的功课，是学会怀念，也学会放下。' },
  { id: 'bu-chao-bu-yong-hua-qian', title: '不潮不用花钱', artist: '林俊杰', category: '华语流行', featured: false, hotComment: '真正的潮流，是自在地做自己的风格。' },
  { id: 'wo-hai-xiang-ta', title: '我还想她', artist: '林俊杰', category: '华语流行', featured: false, hotComment: '嘴上说着算了，心里却还留着她的位置。' },
  { id: 'bei-dui-bei-yong-bao', title: '背对背拥抱', artist: '林俊杰', category: '华语流行', featured: false, hotComment: '两个人离得很近，心却隔着没有说出口的话。' },
  { id: 'always-on-line', title: 'Always on line', artist: '林俊杰', category: '华语流行', featured: false, hotComment: '真正的陪伴，是你需要时我一直在线。' },
  { id: 'xiao-jiu-wo', title: '小酒窝', artist: '林俊杰', category: '华语流行', featured: false, hotComment: '一个笑容，就足够让平凡日子变甜。' },
  { id: 'zui-chi-bi', title: '醉赤壁', artist: '林俊杰', category: '华语流行', featured: false, hotComment: '穿过刀光剑影，最后惦记的仍是那个人。' },
  { id: 'guo-zhe-xin-de-guang', title: '裹着心的光', artist: '林俊杰', category: '华语流行', featured: false, hotComment: '愿你穿过长夜，仍把心里的光好好护住。' },
  { id: 'yuan-yu-chou', title: '愿与愁', artist: '林俊杰', category: '华语流行', featured: false, hotComment: '愿望与忧愁相伴，才像我们认真活过的痕迹。' },
  { id: 'hei-ye-wen-bai-tian', title: '黑夜问白天', artist: '林俊杰', category: '华语流行', featured: false, hotComment: '最深的困惑，常在天亮前独自发问。' },
  { id: 'yi-qian-nian-yi-hou', title: '一千年以后', artist: '林俊杰', category: '华语流行', featured: false, hotComment: '时间可以很远，想念却总能抵达。' },
  { id: 'jiao-huan-yu-sheng', title: '交换余生', artist: '林俊杰', category: '华语流行', featured: false, hotComment: '如果能交换余生，我仍想走进有你的那一种可能。' },
  { id: 'lie-feng-zhong-de-yang-guang', title: '裂缝中的阳光', artist: '林俊杰', category: '华语流行', featured: false, hotComment: '不是所有裂缝都意味着破碎，也可能让光照进来。' },
  { id: 'ta-shuo', title: '她说', artist: '林俊杰', category: '华语流行', featured: false, hotComment: '她把故事说得平静，没说出口的才最让人心疼。' },
  { id: 'na-xie-ni-hen-mao-xian-de-meng', title: '那些你很冒险的梦', artist: '林俊杰', category: '华语流行', featured: false, hotComment: '曾陪你冒险的人，后来是否还在你的梦里。' },
  { id: 'syz-wo-huai-nian-de', title: '我怀念的', artist: '孙燕姿', category: '华语流行', featured: false, hotComment: '真正让人放不下的，常常是那些没能说完的话。' },
  { id: 'syz-kai-shi-dong-le', title: '开始懂了', artist: '孙燕姿', category: '华语流行', featured: false, hotComment: '长大之后才明白，有些离开不是谁的错。' },
  { id: 'syz-yu-jian', title: '遇见', artist: '孙燕姿', category: '华语流行', featured: false, hotComment: '在还不知道你的名字时，命运已经悄悄安排了相逢。' },
  { id: 'syz-wo-bu-nan-guo', title: '我不难过', artist: '孙燕姿', category: '华语流行', featured: false, hotComment: '说着不难过的人，往往把眼泪藏得最深。' },
  { id: 'syz-di-yi-tian', title: '第一天', artist: '孙燕姿', category: '华语流行', featured: false, hotComment: '喜欢从第一天开始，也让每一天都像新的。' },
  { id: 'syz-ban-ju-zai-jian', title: '半句再见', artist: '孙燕姿', category: '华语流行', featured: false, hotComment: '再见只说了半句，另一半留给没有结束的想念。' },
  { id: 'syz-ni-guang', title: '逆光', artist: '孙燕姿', category: '华语流行', featured: false, hotComment: '迎着逆光走的人，终会看见自己的方向。' },
  { id: 'syz-tian-hei-hei', title: '天黑黑', artist: '孙燕姿', category: '华语流行', featured: false, hotComment: '小时候怕天黑，长大后怕的是没人懂得疲惫。' },
  { id: 'syz-yu-tian', title: '雨天', artist: '孙燕姿', category: '华语流行', featured: false, hotComment: '雨声适合想念，也适合把心事慢慢放下。' },
  { id: 'syz-dang-dong-ye-jian-nuan', title: '当冬夜渐暖', artist: '孙燕姿', category: '华语流行', featured: false, hotComment: '最冷的季节过去后，迟到的温柔也会抵达。' },
  { id: 'dzq-duo-yuan-dou-yao-zai-yi-qi', title: '多远都要在一起', artist: '邓紫棋', category: '华语流行', featured: false, hotComment: '距离可以很远，坚定想见你的心不会。' },
  { id: 'dzq-wei-yi', title: '唯一', artist: '邓紫棋', category: '华语流行', featured: false, hotComment: '世界有很多选择，偏偏你成了无可替代。' },
  { id: 'dzq-xi-huan-ni', title: '喜欢你', artist: '邓紫棋', category: '华语流行', featured: false, hotComment: '一句喜欢你，简单得足以让整个夜晚发亮。' },
  { id: 'dzq-lai-zi-tian-tang-de-mo-gui', title: '来自天堂的魔鬼', artist: '邓紫棋', category: '华语流行', featured: false, hotComment: '越迷人的靠近，越可能让人忘记危险。' },
  { id: 'dzq-guang-nian-zhi-wai', title: '光年之外', artist: '邓紫棋', category: '华语流行', featured: false, hotComment: '跨过漫长光年，也想把这一刻唱给你听。' },
  { id: 'dzq-ju-hao', title: '句号', artist: '邓紫棋', category: '华语流行', featured: false, hotComment: '给旧故事一个句号，才有空白写新的开始。' },
  { id: 'dzq-dao-shu', title: '倒数', artist: '邓紫棋', category: '华语流行', featured: false, hotComment: '时间越接近终点，越看得清谁最舍不得。' },
  { id: 'dzq-long-juan-feng', title: '龙卷风', artist: '邓紫棋', category: '华语流行', featured: false, hotComment: '情绪来得像风暴，离开后只剩一地回声。' },
  { id: 'xzq-gang-gang-hao', title: '刚刚好', artist: '薛之谦', category: '华语流行', featured: false, hotComment: '爱到刚刚好，是不再追问也不再打扰。' },
  { id: 'xzq-yan-yuan', title: '演员', artist: '薛之谦', category: '华语流行', featured: false, hotComment: '最累的表演，是假装自己从来没有认真。' },
  { id: 'xzq-ni-hai-yao-wo-zen-yang', title: '你还要我怎样', artist: '薛之谦', category: '华语流行', featured: false, hotComment: '退到无路可退时，只剩一句无奈的询问。' },
  { id: 'xzq-yi-wai', title: '意外', artist: '薛之谦', category: '华语流行', featured: false, hotComment: '你像计划之外的意外，却成了故事里最深的一笔。' },
  { id: 'xzq-fang-yuan-ji-li', title: '方圆几里', artist: '薛之谦', category: '华语流行', featured: false, hotComment: '只要离你近一点，绕再远的路也愿意。' },
  { id: 'xzq-qi-shi', title: '其实', artist: '薛之谦', category: '华语流行', featured: false, hotComment: '其实早就知道答案，只是不愿亲口承认。' },
  { id: 'xzq-pei-ni-qu-liu-lang', title: '陪你去流浪', artist: '薛之谦', category: '华语流行', featured: false, hotComment: '若终点不确定，就把并肩走过当作答案。' },
  { id: 'xzq-tian-wai-lai-wu', title: '天外来物', artist: '薛之谦', category: '华语流行', featured: false, hotComment: '有些相遇从天而降，也让平静的生活彻底失重。' },
  { id: 'xzq-shen-shi', title: '绅士', artist: '薛之谦', category: '华语流行', featured: false, hotComment: '克制的靠近，是怕多一步就失去资格。' },
  { id: 'xzq-xiang-feng-yi-yang', title: '像风一样', artist: '薛之谦', category: '华语流行', featured: false, hotComment: '你来去像风，而我还站在原地记得方向。' },
  { id: 'xzq-wo-hao-xiang-zai-na-jian-guo-ni', title: '我好像在哪见过你', artist: '薛之谦', category: '华语流行', featured: false, hotComment: '熟悉感比名字更早一步认出了你。' },
  { id: 'xzq-ai-mei', title: '暧昧', artist: '薛之谦', category: '华语流行', featured: false, hotComment: '暧昧最动人，也最容易让真心无处安放。' },
  { id: 'xzq-tian-fen', title: '天份', artist: '薛之谦', category: '华语流行', featured: false, hotComment: '爱你像一种天份，忘记却怎么也学不会。' },
  { id: 'xzq-ya-ba', title: '哑巴', artist: '薛之谦', category: '华语流行', featured: false, hotComment: '最沉默的人，心里往往有最响亮的话。' },
  { id: 'wsl-yi-xiao-qing-cheng', title: '一笑倾城', artist: '汪苏泷', category: '华语流行', featured: false, hotComment: '你一笑，喧闹世界突然只剩明亮。' },
  { id: 'wsl-jiu-rang-zhe-da-yu-quan-dou-luo-xia', title: '就让这大雨全都落下', artist: '汪苏泷', category: '华语流行', featured: false, hotComment: '让大雨替我说完，那些忍了很久的话。' },
  { id: 'wsl-wan-you-yin-li', title: '万有引力', artist: '汪苏泷', category: '华语流行', featured: false, hotComment: '人与人的靠近，也有无法解释的万有引力。' },
  { id: 'wsl-ru-guo-ai-wang-le', title: '如果爱忘了', artist: '汪苏泷', category: '华语流行', featured: false, hotComment: '如果爱真的忘了，为什么回忆还会突然发热。' },
  { id: 'wsl-ru-guo-ke-yi', title: '如果可以', artist: '汪苏泷', category: '华语流行', featured: false, hotComment: '如果可以重来，我想把每次错过都改成相遇。' },
  { id: 'wsl-hu-er-jin-xia', title: '忽而今夏', artist: '汪苏泷', category: '华语流行', featured: false, hotComment: '夏天忽然回来，旧时光也跟着吹进心里。' },
  { id: 'wsl-wo-xiang-nian', title: '我想念', artist: '汪苏泷', category: '华语流行', featured: false, hotComment: '想念不是回头，而是某一刻仍会想起。' },
  { id: 'wsl-nian-lun', title: '年轮', artist: '汪苏泷', category: '华语流行', featured: false, hotComment: '时间一圈圈向前，留下的痕迹都叫成长。' },
  { id: 'ljr-yong-qi', title: '勇气', artist: '梁静茹', category: '华语流行', featured: false, hotComment: '爱需要的勇气，是看见不确定仍愿意向前。' },
  { id: 'ljr-hui-hu-xi-de-tong', title: '会呼吸的痛', artist: '梁静茹', category: '华语流行', featured: false, hotComment: '有些失去不会消失，只会藏进每一次呼吸。' },
  { id: 'ljr-qing-ge', title: '情歌', artist: '梁静茹', category: '华语流行', featured: false, hotComment: '一首情歌唱到最后，听见的都是自己的故事。' },
  { id: 'ljr-da-shou-la-xiao-shou', title: '大手拉小手', artist: '梁静茹', category: '华语流行', featured: false, hotComment: '最简单的幸福，是大手牵着小手慢慢走。' },
  { id: 'ljr-ke-xi-bu-shi-ni', title: '可惜不是你', artist: '梁静茹', category: '华语流行', featured: false, hotComment: '最遗憾的不是错过，而是走到最后的人不是你。' },
  { id: 'ljr-gei-wei-lai-de-zi-ji', title: '给未来的自己', artist: '梁静茹', category: '华语流行', featured: false, hotComment: '把今天的坚持，写成一封寄给未来的信。' },
  { id: 'ljr-nuan-nuan', title: '暖暖', artist: '梁静茹', category: '华语流行', featured: false, hotComment: '被认真放在心上，日子自然会变得暖暖。' },
  { id: 'ljr-fen-shou-kuai-le', title: '分手快乐', artist: '梁静茹', category: '华语流行', featured: false, hotComment: '祝你分手快乐，也祝你重新学会爱自己。' },
  { id: 'ljr-chong-bai', title: '崇拜', artist: '梁静茹', category: '华语流行', featured: false, hotComment: '曾经的崇拜太满，才让告别显得那么空。' },
  { id: 'ljr-ning-xia', title: '宁夏', artist: '梁静茹', category: '华语流行', featured: false, hotComment: '宁静的夏夜里，晚风会替人保管温柔。' },
  { id: 'tz-jiu-shi-ai-ni', title: '就是爱你', artist: '陶喆', category: '华语流行', featured: false, hotComment: '喜欢不需要复杂理由，就是确定地爱你。' },
  { id: 'tz-ai-hen-jian-dan', title: '爱很简单', artist: '陶喆', category: '华语流行', featured: false, hotComment: '当真心足够清楚，爱原来可以很简单。' },
  { id: 'tz-hu-die', title: '蝴蝶', artist: '陶喆', category: '华语流行', featured: false, hotComment: '经历蜕变的人，终会拥有展开翅膀的勇气。' },
  { id: 'tz-zhao-zi-ji', title: '找自己', artist: '陶喆', category: '华语流行', featured: false, hotComment: '绕过世界的喧闹，最后还是要找回自己。' },
  { id: 'tz-xiao-zhen-gu-niang', title: '小镇姑娘', artist: '陶喆', category: '华语流行', featured: false, hotComment: '小镇装得下青春，却装不下想去远方的心。' },
  { id: 'tz-ai-wo-hai-shi-ta', title: '爱我还是他', artist: '陶喆', category: '华语流行', featured: false, hotComment: '答案越迟疑，越说明有人已经受伤。' },
  { id: 'tz-pu-tong-peng-you', title: '普通朋友', artist: '陶喆', category: '华语流行', featured: false, hotComment: '最难的位置，是比陌生熟悉、比恋人疏远。' },
  { id: 'tz-liu-sha', title: '流沙', artist: '陶喆', category: '华语流行', featured: false, hotComment: '越想抓紧的感情，越像流沙从指缝离开。' },
  { id: 'wlh-ai-cuo', title: '爱错', artist: '王力宏', category: '华语流行', featured: false, hotComment: '爱错不是白费，只是用疼痛认清适合。' },
  { id: 'wlh-ni-bu-zhi-dao-de-shi', title: '你不知道的事', artist: '王力宏', category: '华语流行', featured: false, hotComment: '你不知道的事，都藏在我没说出口的沉默里。' },
  { id: 'wlh-yi-ran-ai-ni', title: '依然爱你', artist: '王力宏', category: '华语流行', featured: false, hotComment: '时间改变许多事，却没改掉依然爱你的习惯。' },
  { id: 'wlh-xu-yao-ren-pei', title: '需要人陪', artist: '王力宏', category: '华语流行', featured: false, hotComment: '再热闹的城市，也有人在等一句陪伴。' },
  { id: 'wlh-da-cheng-xiao-ai', title: '大城小爱', artist: '王力宏', category: '华语流行', featured: false, hotComment: '城市很大，两个人的小爱也能自成宇宙。' },
  { id: 'xs-su-yan', title: '素颜', artist: '许嵩', category: '华语流行', featured: false, hotComment: '最真实的喜欢，是看见素颜也觉得心动。' },
  { id: 'xs-you-he-bu-ke', title: '有何不可', artist: '许嵩', category: '华语流行', featured: false, hotComment: '只要是和你一起，任性一次又有何不可。' },
  { id: 'xs-su-di', title: '宿敌', artist: '许嵩', category: '华语流行', featured: false, hotComment: '有些人像宿敌，一生都在彼此故事里纠缠。' },
  { id: 'xs-ru-guo-dang-shi', title: '如果当时', artist: '许嵩', category: '华语流行', featured: false, hotComment: '如果当时勇敢一点，后来会不会换一种结局。' },
  { id: 'xs-qing-ming-yu-shang', title: '清明雨上', artist: '许嵩', category: '华语流行', featured: false, hotComment: '细雨落在旧城，也落在没能寄出的思念上。' },
  { id: 'xs-zui-jia-ge-shou', title: '最佳歌手', artist: '许嵩', category: '华语流行', featured: false, hotComment: '唱得再像最佳歌手，也唱不回离开的听众。' },
  { id: 'xs-lu-zhou-yue', title: '庐州月', artist: '许嵩', category: '华语流行', featured: false, hotComment: '一轮庐州月，照着故乡，也照着远方人的心。' },
  { id: 'cyx-fu-shi-shan-xia', title: '富士山下', artist: '陈奕迅', category: '华语流行', featured: false, hotComment: '喜欢像富士山，只能远望，不能据为己有。' },
  { id: 'cyx-ai-qing-zhuan-yi', title: '爱情转移', artist: '陈奕迅', category: '华语流行', featured: false, hotComment: '人可以转身离开，爱过的痕迹却不会立刻转移。' },
  { id: 'zrz-ru-guo-ne', title: '如果呢', artist: '郑润泽', category: '华语流行', featured: false, hotComment: '一句如果呢，装着所有没发生的可能。' },
  { id: 'zrz-yu-shi', title: '于是', artist: '郑润泽', category: '华语流行', featured: false, hotComment: '于是我们继续生活，也继续偶尔想起彼此。' },
  { id: 'zrz-shun', title: '瞬', artist: '郑润泽', category: '华语流行', featured: false, hotComment: '有些瞬间很短，却足够在记忆里停留很久。' },
  { id: 'zrz-xia-xiang', title: '遐想', artist: '郑润泽', category: '华语流行', featured: false, hotComment: '让思绪走远一点，也许会遇见另一种自己。' },
];

export const SONG_CATEGORIES = ['全部', ...new Set(SONGS.map((song) => song.category))];
